### ISSUE TITLE
Issue running demos on fresh install

### ISSUE THREAD

**Issue by paulommaia** [TeamIRI/darkshield-api-demos#1]
Hi,

I'm having the following error when running the pdf-image demo:

![image](https://user-images.githubusercontent.com/61968534/130641304-140bf3de-9409-4e11-96ca-90e93dbaedf1.png)

Running sortcl /v returns:

```
CoSort 10.0.1  R100201222-2357 64-bit Copyright 1978,2020 IRI, Inc. www.iri.com
2021-08-24 17:05:41 #00000.0000 4 CPU Linux x86_64
Expiration Date: 2021-09-15
```

Plankton is running and I can access its docs. 

I've tried adding sortcl to the system path and to the python path but it didn't work. How do I fix this? 
Thanks,

**Comment by dimakula** [comment]
Hi Paulo,

Can you confirm that your $PATH environment variable contains the bin directory for sortcl on the terminal shell that you used to launch the Plankton API? It may be the case that the $PATH in the terminal was not updated yet.

**Comment by paulommaia** [comment]
Hi @dimakula 

That was the issue: I needed to add to the shell launching the API, not the one running Python

export PATH="/home/ubuntu/cosort100/bin/:$PATH" 

Thanks!
